### ISSUE TITLE
chrome headless printing 

### ISSUE THREAD

**Issue by phaustin** [eoas-ubc/eoas_tlef#31]
- [x] review these [trio references](https://github.com/eoas-ubc/trio_chrome#trio)

- [x] fork https://github.com/eoas-ubc/trio_chrome.git and follow install instructions

- [x]  add chromium install command borrowed from pypeteer

**Comment by hcolclou** [comment]
The trio references link seems broken

**Comment by phaustin** [comment]
fixed -- they're just the bottom part of the paged_trio readme pre-move

**Comment by hcolclou** [comment]
I think this can be checked off now

**Comment by phaustin** [comment]
closed by https://github.com/eoas-ubc/trio_chrome
