### ISSUE TITLE
pdf printing using pagedjs

### ISSUE THREAD

**Issue by phaustin** [eoas-ubc/eoas_tlef#4]
- [x] clone [paged_trio](https://github.com/eoas-ubc/paged_trio.git)
- [x] install and run the nbconvert [printit template](https://github.com/eoas-ubc/paged_trio/tree/master/pagelib/project_templates/nbconvert/templates/printit)
- [x] clone the two themes that are used by [pyman](https://github.com/eoas-ubc/eoas_tlef/tree/master/pyman)  ([sphinx_rtd_theme](https://github.com/readthedocs/sphinx_rtd_theme)) and [quantecon-example](https://github.com/eoas-ubc/eoas_tlef/tree/master/quantecon-example/book) ([pydata-sphinx-theme](https://github.com/pandas-dev/pydata-sphinx-theme))
- [x] build these two examples with local imports of the sphinx themes to see how the jinja2 templates are used to create the html
- [x] write our own sphinx theme that uses the header information from the  [printit template](https://github.com/eoas-ubc/paged_trio/blob/master/pagelib/project_templates/nbconvert/templates/printit/index.html.j2) instead, so that we add  pagedjs headers and pagebreaks to the two manuals
- [x] commit the new theme (called paged_html?) into its own github repository so it's pip installable.
- [x] modify the single notebook example at https://github.com/phaustin/MyST-NB/tree/utf_issue/docs/examples/utf_bug so it uses the theme -- i.e. change [this line](https://github.com/phaustin/MyST-NB/blob/ea9ac2230ca4cfcc08c269f58b41b00d826da597/docs/examples/utf_bug/conf.py#L76) to "paged_html" and change the environment.yml file to install the new theme  in [the pip section](https://github.com/phaustin/MyST-NB/blob/ea9ac2230ca4cfcc08c269f58b41b00d826da597/docs/examples/utf_bug/environment.yml#L17-L18).
- [x] Substitute the quiz2 notebook for the appdx1 notebook
- [x] post readme and  invite collaborators:  https://github.com/executablebooks/MyST-NB/issues/201

**Comment by hcolclou** [comment]
This is ready for an alpha release

**Comment by hcolclou** [comment]
I think this can be checked off now
